export const DEFAULT_TASKS = [
    'ate something',
    'ate something healthy',
    'cooked',
    'got out of the bed',
    'showered',
    'went to the gym',
    'worked out',
    'went for a walk',
    'played video games',
    'played with my dog',
    'played with my cat',
    'fed the cat',
    'fed the dog',
    'called my mom',
    'hanged out with my friends',
    'went to work',
    'ran errands',
    'washed the dishes',
    'watered the plants',
    'gardened',
    'drank water',
    'didn’t buy anything',
    'tidied my desk',
    'tidied the living room',
    'fixed my computer',
    'draw',
    'crocheted',
    'knitted',
    'painted',
    'wrote',
    'played guitar',
    'played piano',
    'did a push up',
    'avoided social networks',
    'read a book',
    'read a magazine',
    'listened to music',
    'made some researches',
    'took a dentist appointment',
    'took a doctor appointment',
    'took my medication',
];